//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public Actividad()
        {
            this.Refinanciacions = new HashSet<Refinanciacion>();
        }
    
        public int idActividad { get; set; }
        public int idTipoActividad { get; set; }
        public int idDeuda { get; set; }
        public int idGestor { get; set; }
        public int idResultado { get; set; }
        public System.DateTime fecha { get; set; }
        public string detalles { get; set; }
    
        public virtual Deuda Deuda { get; set; }
        public virtual TipoActividad TipoActividad { get; set; }
        public virtual ICollection<Refinanciacion> Refinanciacions { get; set; }
    }
}
