//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalificacionDato
    {
        public int idCalificacion { get; set; }
        public int idDato { get; set; }
        public decimal valorCalificacion { get; set; }
        public string valorDato { get; set; }
        public Nullable<decimal> valorDatoMinimo { get; set; }
        public Nullable<decimal> valorDatoMaximo { get; set; }
    
        public virtual DatoDeudor DatoDeudor { get; set; }
        public virtual DatoGestor DatoGestor { get; set; }
    }
}
