//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartera
    {
        public Cartera()
        {
            this.Deudas = new HashSet<Deuda>();
            this.PoliticaCobranzas = new HashSet<PoliticaCobranza>();
        }
    
        public int idCartera { get; set; }
        public int idAcreedor { get; set; }
        public string nombre { get; set; }
        public int esVencida { get; set; }
        public int porcentajeGanancia { get; set; }
        public string detalles { get; set; }
        public int cantidadDeudas { get; set; }
    
        public virtual Acreedor Acreedor { get; set; }
        public virtual Parametro Parametro { get; set; }
        public virtual ICollection<Deuda> Deudas { get; set; }
        public virtual ICollection<PoliticaCobranza> PoliticaCobranzas { get; set; }
    }
}
