//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel;

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartera
    {
        public Cartera()
        {
            this.Deudas = new HashSet<Deuda>();
            this.PoliticaCobranzas = new HashSet<PoliticaCobranza>();
        }
    
        [DisplayName("Id")]
        public int idCartera { get; set; }
        [DisplayName("ID Acreedor")]
        public int idAcreedor { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [DisplayName("Tipo")]
        public int esVencida { get; set; }
        [DisplayName("Porcentaje ganancia")]
        public int porcentajeGanancia { get; set; }
        [DisplayName("Detalles")]
        public string detalles { get; set; }
        [DisplayName("Cantidad de deudas")]
        public int cantidadDeudas { get; set; }
        [DisplayName("Acreedor")]
        public virtual Acreedor Acreedor { get; set; }
        [DisplayName("Deudas")]
        public virtual ICollection<Deuda> Deudas { get; set; }
        [DisplayName("Políticas de Cobranza")]
        public virtual ICollection<PoliticaCobranza> PoliticaCobranzas { get; set; }
    }
}
