//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuota
    {
        public int idCuota { get; set; }
        public int idRefinanciacion { get; set; }
        public System.DateTime fechaPactada { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
    
        public virtual Refinanciacion Refinanciacion { get; set; }
    }
}
