//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Dato
    {
        public Dato()
        {
            this.CalificacionDatoes = new HashSet<CalificacionDato>();
        }
        
        [DisplayName("Id")]
        public int idDato { get; set; }
        [DisplayName("Tipo")]
        public string tipo { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [DisplayName("Calificaciones del dato")]
        public virtual ICollection<CalificacionDato> CalificacionDatoes { get; set; }
    }
}
