//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatoGestor
    {
        public DatoGestor()
        {
            this.CalificacionDatoes = new HashSet<CalificacionDato>();
        }
    
        public int idDato { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<CalificacionDato> CalificacionDatoes { get; set; }
    }
}
