//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deudor
    {
        public Deudor()
        {
            this.Deudas = new HashSet<Deuda>();
        }
    
        public int idDeudor { get; set; }
        public string nombres { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public int tipoDocumento { get; set; }
        public string numeroDocumento { get; set; }
        public string telefonoPersonal { get; set; }
        public string telefonoDomicilio { get; set; }
        public string telefonoTrabajo { get; set; }
        public string correo { get; set; }
        public string direccion { get; set; }
        public Nullable<int> poseeTrabajo { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public int numeroTotalDeudas { get; set; }
        public decimal totalAdeudado { get; set; }
        public Nullable<int> estadoCivil { get; set; }
        public Nullable<int> numeroHijos { get; set; }
        public Nullable<int> sexo { get; set; }
        public string detalles { get; set; }
    
        public virtual ICollection<Deuda> Deudas { get; set; }
        public virtual Parametro Parametro { get; set; }
        public virtual Parametro Parametro1 { get; set; }
        public virtual Parametro Parametro2 { get; set; }
    }
}
