//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Deudor
    {
        public Deudor()
        {
            this.Deudas = new HashSet<Deuda>();
        }

        [DisplayName("Id")]
        public int idDeudor { get; set; }
        [DisplayName("Nombres")]
        public string nombres { get; set; }
        [DisplayName("Apellido Paterno")]
        public string apellidoPaterno { get; set; }
        [DisplayName("Apellido Materno")]
        public string apellidoMaterno { get; set; }
        [DisplayName("Tipo de documento")]
        public int tipoDocumento { get; set; }
        [DisplayName("Número de documento")]
        public string numeroDocumneto { get; set; }
        [DisplayName("Teléfono personal")]
        public string telefonoPersonal { get; set; }
        [DisplayName("Teléfono de domicilio")]
        public string telefonoDomicilio { get; set; }
        [DisplayName("Teléfono de trabajo")]
        public string telefonoTrabajo { get; set; }
        [DisplayName("Correo electrónico")]
        public string correo { get; set; }
        [DisplayName("Dirección")]
        public string direccion { get; set; }
        [DisplayName("Posee trabajo")]
        public Nullable<int> poseeTrabajo { get; set; }
        [DisplayName("Fecha de nacimiento")]
        public System.DateTime fechaNacimiento { get; set; }
        [DisplayName("Número total de deudas")]
        public int numeroTotalDeudas { get; set; }
        [DisplayName("Total adeudado")]
        public decimal totalAdeudado { get; set; }
        [DisplayName("Estado civil")]
        public Nullable<int> estadoCivil { get; set; }
        [DisplayName("Número de hijos")]
        public Nullable<int> numeroHijos { get; set; }
        [DisplayName("Sexo")]
        public Nullable<int> sexo { get; set; }
        [DisplayName("Detalles")]
        public string detalles { get; set; }
        
        [DisplayName("Deudas")]
        public virtual ICollection<Deuda> Deudas { get; set; }
    }
}
