//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class GestorXDeuda
    {
        [DisplayName("Id")]
        public int idGestor { get; set; }
        [DisplayName("Id deuda")]
        public int idDeuda { get; set; }
        [DisplayName("Fecha de asignación")]
        public System.DateTime fechaAsignacion { get; set; }
        [DisplayName("Éxito")]
        public int exito { get; set; }

        [DisplayName("Deuda")]
        public virtual Deuda Deuda { get; set; }
        [DisplayName("Gestor")]
        public virtual Gestor Gestor { get; set; }
    }
}
