//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parametro
    {
        [DisplayName("Id")]
        public int idParametro { get; set; }
        [DisplayName("Tipo")]
        public string tipo { get; set; }
        [DisplayName("Valor")]
        public string valor { get; set; }
        [DisplayName("Valor Numérico")]
        public Nullable<decimal> valorNum { get; set; }
        [DisplayName("Id Padre")]
        public Nullable<int> idPadre { get; set; }
        [DisplayName("Código único")]   
        public string codUnico { get; set; }
    }
}
