//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permiso
    {
        public Permiso()
        {
            this.Rols = new HashSet<Rol>();
        }
    
        public int idPermiso { get; set; }
        public string nombre { get; set; }
        public string funcionalidad { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Rol> Rols { get; set; }
    }
}
