//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class PoliticaCobranzaXTipoActividad
    {
        [DisplayName("Id")]
        public int idPoliticaCobranza { get; set; }
        [DisplayName("Id Tipo de actividad")]
        public int idTipoActividad { get; set; }
        [DisplayName("Paso N°")]
        public int numeroPaso { get; set; }
        [DisplayName("Fecha de inicio")]
        public System.DateTime fechaInicio { get; set; }
        [DisplayName("Fecha de fin")]
        public System.DateTime fechaFin { get; set; }

        [DisplayName("Política de cobranza")]
        public virtual PoliticaCobranza PoliticaCobranza { get; set; }
        [DisplayName("Tipo de Actividad")]
        public virtual TipoActividad TipoActividad { get; set; }
    }
}
