//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticaCobranza
    {
        public PoliticaCobranza()
        {
            this.PoliticaCobranzaXTipoActividads = new HashSet<PoliticaCobranzaXTipoActividad>();
        }
    
        public int idPoliticaCobranza { get; set; }
        public int idCartera { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int obligatoria { get; set; }
        public Nullable<decimal> interesRefinanciacion { get; set; }
        public Nullable<int> maximoCuotasRefinanciacion { get; set; }
        public Nullable<decimal> interesDiarioPropio { get; set; }
    
        public virtual Cartera Cartera { get; set; }
        public virtual ICollection<PoliticaCobranzaXTipoActividad> PoliticaCobranzaXTipoActividads { get; set; }
    }
}
