//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliticaCobranzaXTipoActividad
    {
        public int idPoliticaCobranza { get; set; }
        public int idTipoActividad { get; set; }
        public int numeroPaso { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFin { get; set; }
    
        public virtual PoliticaCobranza PoliticaCobranza { get; set; }
        public virtual TipoActividad TipoActividad { get; set; }
    }
}
