//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class Refinanciacion
    {
        public Refinanciacion()
        {
            this.Cuotas = new HashSet<Cuota>();
        }

        [DisplayName("Id")]
        public int idRefinanciacion { get; set; }
        [DisplayName("Id Actividad")]
        public int idActividad { get; set; }
        [DisplayName("Id Deuda")]
        public int idDeuda { get; set; }
        [DisplayName("Número de cuotas")]
        public int numeroCuotas { get; set; }
        [DisplayName("Monto de cuota")]
        public decimal montoCuota { get; set; }
        [DisplayName("Moneda")]
        public int moneda { get; set; }
        [DisplayName("Fecha de refinanciación")]
        public System.DateTime fechaRefinanciacion { get; set; }
        [DisplayName("Periodicidad (Meses)")]
        public int periodicidadMeses { get; set; }
        [DisplayName("Tasa de Interés")]
        public decimal interes { get; set; }

        [DisplayName("Actividad")]
        public virtual Actividad Actividad { get; set; }
        [DisplayName("Cuotas")]
        public virtual ICollection<Cuota> Cuotas { get; set; }
        [DisplayName("Deuda")]
        public virtual Deuda Deuda { get; set; }
    }
}
