//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Refinanciacion
    {
        public Refinanciacion()
        {
            this.Cuotas = new HashSet<Cuota>();
        }
    
        public int idRefinanciacion { get; set; }
        public int idActividad { get; set; }
        public int idDeuda { get; set; }
        public int numeroCuotas { get; set; }
        public decimal montoCuota { get; set; }
        public int moneda { get; set; }
        public System.DateTime fechaRefinanciacion { get; set; }
        public int periodicidadMeses { get; set; }
        public decimal interes { get; set; }
    
        public virtual Actividad Actividad { get; set; }
        public virtual ICollection<Cuota> Cuotas { get; set; }
        public virtual Deuda Deuda { get; set; }
        public virtual Parametro Parametro { get; set; }
    }
}
