//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol
    {
        public Rol()
        {
            this.RolXPermisoes = new HashSet<RolXPermiso>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int idRol { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public int estado { get; set; }
    
        public virtual ICollection<RolXPermiso> RolXPermisoes { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
