//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoActividad
    {
        public TipoActividad()
        {
            this.Actividads = new HashSet<Actividad>();
            this.PoliticaCobranzaXTipoActividads = new HashSet<PoliticaCobranzaXTipoActividad>();
        }
    
        public int idTipoActividad { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<Actividad> Actividads { get; set; }
        public virtual ICollection<PoliticaCobranzaXTipoActividad> PoliticaCobranzaXTipoActividads { get; set; }
    }
}
