//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    
    public partial class TipoActividad
    {
        public TipoActividad()
        {
            this.Actividads = new HashSet<Actividad>();
            this.PoliticaCobranzaXTipoActividads = new HashSet<PoliticaCobranzaXTipoActividad>();
        }

        [DisplayName("Cuotas")]            
        public int idTipoActividad { get; set; }
        [DisplayName("Nombre")]
        public string nombre { get; set; }
        [DisplayName("Descripción")]
        public string descripcion { get; set; }

        [DisplayName("Actividades")]
        public virtual ICollection<Actividad> Actividads { get; set; }
        [DisplayName("Política de Cobranza")]
        public virtual ICollection<PoliticaCobranzaXTipoActividad> PoliticaCobranzaXTipoActividads { get; set; }
    }
}
