//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecaudaSoft.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int idUsuario { get; set; }
        public Nullable<int> idAcreedor { get; set; }
        public Nullable<int> idGestor { get; set; }
        public int idRol { get; set; }
        public string nombreUsuario { get; set; }
        public string contrasena { get; set; }
        public int tipoUsuario { get; set; }
        public int estado { get; set; }
        public string correo { get; set; }
    
        public virtual Acreedor Acreedor { get; set; }
        public virtual Gestor Gestor { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
